name: "CI"

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/script.yml
    with:
      script: "lint"

  unit:
    needs: [build,lint]
    uses: ./.github/workflows/script.yml
    with:
      script: "test:unit"

  integration:
    needs: [build,lint]
    uses: ./.github/workflows/script.yml
    with:
      script: "test:integration"

  build:
    uses: ./.github/workflows/script.yml
    with:
      script: "build"
